name: pytorch-stacked-hourglass
channels:
  - pytorch
dependencies:
  - python=3.7.4
  - pip=20.0.2
  - cudatoolkit=10.0
  - "pytorch=1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0"
  - "torchvision=0.3.0=cuda100py37h72fc40a_0"
  - pip:
      - -r requirements.txt
